services:
  postgres:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: mery
    ports:
      - "5432:5432"
 
volumes:
  pgdata:

# services:
#  postgres:
#    image: postgres:latest
# services: (Dienst-Definition)
# Erstellt einen Service namens postgres, basierend auf dem neuesten PostgreSQL-Image
# Wenn das Image nicht vorhanden ist, wird es automatisch aus Docker Hub heruntergeladen

#     volumes:
#      - pgdata:/var/lib/postgresql/data
# volumes: (Persistente Daten)
# Erstellt einen persistenten Speicher (pgdata) für die PostgreSQL-Datenbank
# Daten bleiben erhalten, auch wenn der Container gestoppt oder neu gestartet wird.

#    environment:
#      POSTGRES_PASSWORD: password
#      POSTGRES_USER: jannik
# environment: (Umgebungsvariablen)
# Setzt den Datenbank-Benutzer auf mery
# Setzt das Passwort für den Benutzer auf password

#   ports:
#      - "5432:5432"
# ports: (Zugriff auf die Datenbank von außen)
# Der Port 5432 im Container wird auf 5432 des Hosts weitergeleitet
# Dadurch kannst du lokal mit localhost:5432 auf PostgreSQL zugreifen (z. B. mit Drizzle oder psql)

# volumes:
#  pgdata:
# volumes: (Speicher für persistente Daten)
# Erstellt einen benannten Volume (pgdata), damit die Datenbank auch nach dem Neustart erhalten bleibt
# Der Speicherort liegt außerhalb des Containers und bleibt bestehen, selbst wenn der Container gelöscht wird
